export const ControllerKey = Symbol('Controller')
export const RequestKey = Symbol('Request')
export const ParamKey = Symbol('Param')
export const QueryKey = Symbol('Query')
export const BodyKey = Symbol('Body')
export const ViewKey = Symbol('View')
export const StatusKey = Symbol('Status')
export const HeaderKey = Symbol('Header')
